included:
  - Mobile
excluded:
  - Carthage
  - Pods
  - Mobile/App/Resources/R.generated.swift
  
disabled_rules:
  - nesting
  - weak_delegate
  - multiple_closures_with_trailing_closure
  - implicit_getter
opt_in_rules:
  - empty_count
  - toggle_bool
  - empty_string
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - last_where
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header

force_cast: error
force_try: error

line_length: 300

variable_name_max_length:
  - 45
  - 60

function_parameter_count:
  - 10
  - 15

function_body_length:
  - 250
  - 500

type_body_length:
  - 1000
  - 1500

file_length:
  - 1000
  - 1500

identifier_name:
  max_length:
    warning: 55
    error: 65
  min_length:
    warning: 1
  
type_name:
  max_length:
    warning: 55
    error: 65
  min_length:
    warning: 1

large_tuple:
  - 3
  - 4

cyclomatic_complexity:
  - 15
  - 25


