//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map(Locale.init)
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try font.validate()
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 7 storyboards.
  struct storyboard {
    /// Storyboard `Home`.
    static let home = _R.storyboard.home()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Login`.
    static let login = _R.storyboard.login()
    /// Storyboard `MainTabBar`.
    static let mainTabBar = _R.storyboard.mainTabBar()
    /// Storyboard `Notifications`.
    static let notifications = _R.storyboard.notifications()
    /// Storyboard `Promotions`.
    static let promotions = _R.storyboard.promotions()
    /// Storyboard `Sports`.
    static let sports = _R.storyboard.sports()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Home", bundle: ...)`
    static func home(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.home)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Login", bundle: ...)`
    static func login(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.login)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "MainTabBar", bundle: ...)`
    static func mainTabBar(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.mainTabBar)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Notifications", bundle: ...)`
    static func notifications(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.notifications)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Promotions", bundle: ...)`
    static func promotions(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.promotions)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "Sports", bundle: ...)`
    static func sports(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.sports)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    /// This `R.color.colorGuide` struct is generated, and contains static references to 0 colors.
    struct colorGuide {
      /// This `R.color.colorGuide.neutral` struct is generated, and contains static references to 10 colors.
      struct neutral {
        /// Color `neutral100`.
        static let neutral100 = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Neutral/neutral100")
        /// Color `neutral200`.
        static let neutral200 = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Neutral/neutral200")
        /// Color `neutral300`.
        static let neutral300 = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Neutral/neutral300")
        /// Color `neutral400`.
        static let neutral400 = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Neutral/neutral400")
        /// Color `neutral500`.
        static let neutral500 = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Neutral/neutral500")
        /// Color `neutral600`.
        static let neutral600 = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Neutral/neutral600")
        /// Color `neutral700`.
        static let neutral700 = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Neutral/neutral700")
        /// Color `neutral800`.
        static let neutral800 = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Neutral/neutral800")
        /// Color `neutral900`.
        static let neutral900 = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Neutral/neutral900")
        /// Color `white`.
        static let white = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Neutral/white")

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "neutral100", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func neutral100(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.neutral.neutral100, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "neutral200", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func neutral200(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.neutral.neutral200, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "neutral300", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func neutral300(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.neutral.neutral300, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "neutral400", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func neutral400(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.neutral.neutral400, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "neutral500", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func neutral500(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.neutral.neutral500, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "neutral600", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func neutral600(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.neutral.neutral600, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "neutral700", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func neutral700(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.neutral.neutral700, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "neutral800", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func neutral800(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.neutral.neutral800, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "neutral900", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func neutral900(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.neutral.neutral900, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "white", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func white(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.neutral.white, compatibleWith: traitCollection)
        }
        #endif

        fileprivate init() {}
      }

      /// This `R.color.colorGuide.primary` struct is generated, and contains static references to 2 colors.
      struct primary {
        /// Color `primary200`.
        static let primary200 = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Primary/primary200")
        /// Color `primary400`.
        static let primary400 = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Primary/primary400")

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "primary200", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func primary200(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.primary.primary200, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "primary400", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func primary400(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.primary.primary400, compatibleWith: traitCollection)
        }
        #endif

        fileprivate init() {}
      }

      /// This `R.color.colorGuide.secondary` struct is generated, and contains static references to 2 colors.
      struct secondary {
        /// Color `secondary200`.
        static let secondary200 = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Secondary/secondary200")
        /// Color `secondary400`.
        static let secondary400 = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Secondary/secondary400")

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "secondary200", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func secondary200(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.secondary.secondary200, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "secondary400", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func secondary400(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.secondary.secondary400, compatibleWith: traitCollection)
        }
        #endif

        fileprivate init() {}
      }

      /// This `R.color.colorGuide.semantic` struct is generated, and contains static references to 3 colors.
      struct semantic {
        /// Color `error`.
        static let error = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Semantic/error")
        /// Color `success`.
        static let success = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Semantic/success")
        /// Color `warning`.
        static let warning = Rswift.ColorResource(bundle: R.hostingBundle, name: "ColorGuide/Semantic/warning")

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "error", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func error(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.semantic.error, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "success", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func success(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.semantic.success, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIColor(named: "warning", bundle: ..., traitCollection: ...)`
        @available(tvOS 11.0, *)
        @available(iOS 11.0, *)
        static func warning(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
          return UIKit.UIColor(resource: R.color.colorGuide.semantic.warning, compatibleWith: traitCollection)
        }
        #endif

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.entitlements` struct is generated, and contains static references to 1 properties.
  struct entitlements {
    struct keychainAccessGroups {
      static let appIdentifierPrefixComAdjarabetMobileCredentials = infoPlistString(path: ["keychain-access-groups"], key: "$(AppIdentifierPrefix)com.adjarabet.Mobile.credentials") ?? "$(AppIdentifierPrefix)com.adjarabet.Mobile.credentials"

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.file` struct is generated, and contains static references to 21 files.
  struct file {
    /// Resource file `FiraGO-Bold.ttf`.
    static let firaGOBoldTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-Bold", pathExtension: "ttf")
    /// Resource file `FiraGO-Book.ttf`.
    static let firaGOBookTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-Book", pathExtension: "ttf")
    /// Resource file `FiraGO-Eight.ttf`.
    static let firaGOEightTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-Eight", pathExtension: "ttf")
    /// Resource file `FiraGO-ExtraBold.ttf`.
    static let firaGOExtraBoldTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-ExtraBold", pathExtension: "ttf")
    /// Resource file `FiraGO-ExtraLight.ttf`.
    static let firaGOExtraLightTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-ExtraLight", pathExtension: "ttf")
    /// Resource file `FiraGO-Four.ttf`.
    static let firaGOFourTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-Four", pathExtension: "ttf")
    /// Resource file `FiraGO-Hair.ttf`.
    static let firaGOHairTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-Hair", pathExtension: "ttf")
    /// Resource file `FiraGO-Heavy.ttf`.
    static let firaGOHeavyTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-Heavy", pathExtension: "ttf")
    /// Resource file `FiraGO-Light.ttf`.
    static let firaGOLightTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-Light", pathExtension: "ttf")
    /// Resource file `FiraGO-Medium.ttf`.
    static let firaGOMediumTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-Medium", pathExtension: "ttf")
    /// Resource file `FiraGO-Regular.ttf`.
    static let firaGORegularTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-Regular", pathExtension: "ttf")
    /// Resource file `FiraGO-SemiBold.ttf`.
    static let firaGOSemiBoldTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-SemiBold", pathExtension: "ttf")
    /// Resource file `FiraGO-Thin.ttf`.
    static let firaGOThinTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-Thin", pathExtension: "ttf")
    /// Resource file `FiraGO-Two.ttf`.
    static let firaGOTwoTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-Two", pathExtension: "ttf")
    /// Resource file `FiraGO-UltraLight.ttf`.
    static let firaGOUltraLightTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "FiraGO-UltraLight", pathExtension: "ttf")
    /// Resource file `PantonAM-Bold.otf`.
    static let pantonAMBoldOtf = Rswift.FileResource(bundle: R.hostingBundle, name: "PantonAM-Bold", pathExtension: "otf")
    /// Resource file `PantonAM-ExtraBold.otf`.
    static let pantonAMExtraBoldOtf = Rswift.FileResource(bundle: R.hostingBundle, name: "PantonAM-ExtraBold", pathExtension: "otf")
    /// Resource file `PantonAM-Regular.otf`.
    static let pantonAMRegularOtf = Rswift.FileResource(bundle: R.hostingBundle, name: "PantonAM-Regular", pathExtension: "otf")
    /// Resource file `PantonMtav3-Bold.otf`.
    static let pantonMtav3BoldOtf = Rswift.FileResource(bundle: R.hostingBundle, name: "PantonMtav3-Bold", pathExtension: "otf")
    /// Resource file `PantonMtav3-ExtraBold.otf`.
    static let pantonMtav3ExtraBoldOtf = Rswift.FileResource(bundle: R.hostingBundle, name: "PantonMtav3-ExtraBold", pathExtension: "otf")
    /// Resource file `PantonMtav3-Regular.otf`.
    static let pantonMtav3RegularOtf = Rswift.FileResource(bundle: R.hostingBundle, name: "PantonMtav3-Regular", pathExtension: "otf")

    /// `bundle.url(forResource: "FiraGO-Bold", withExtension: "ttf")`
    static func firaGOBoldTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGOBoldTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "FiraGO-Book", withExtension: "ttf")`
    static func firaGOBookTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGOBookTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "FiraGO-Eight", withExtension: "ttf")`
    static func firaGOEightTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGOEightTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "FiraGO-ExtraBold", withExtension: "ttf")`
    static func firaGOExtraBoldTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGOExtraBoldTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "FiraGO-ExtraLight", withExtension: "ttf")`
    static func firaGOExtraLightTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGOExtraLightTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "FiraGO-Four", withExtension: "ttf")`
    static func firaGOFourTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGOFourTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "FiraGO-Hair", withExtension: "ttf")`
    static func firaGOHairTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGOHairTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "FiraGO-Heavy", withExtension: "ttf")`
    static func firaGOHeavyTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGOHeavyTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "FiraGO-Light", withExtension: "ttf")`
    static func firaGOLightTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGOLightTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "FiraGO-Medium", withExtension: "ttf")`
    static func firaGOMediumTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGOMediumTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "FiraGO-Regular", withExtension: "ttf")`
    static func firaGORegularTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGORegularTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "FiraGO-SemiBold", withExtension: "ttf")`
    static func firaGOSemiBoldTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGOSemiBoldTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "FiraGO-Thin", withExtension: "ttf")`
    static func firaGOThinTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGOThinTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "FiraGO-Two", withExtension: "ttf")`
    static func firaGOTwoTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGOTwoTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "FiraGO-UltraLight", withExtension: "ttf")`
    static func firaGOUltraLightTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.firaGOUltraLightTtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "PantonAM-Bold", withExtension: "otf")`
    static func pantonAMBoldOtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.pantonAMBoldOtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "PantonAM-ExtraBold", withExtension: "otf")`
    static func pantonAMExtraBoldOtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.pantonAMExtraBoldOtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "PantonAM-Regular", withExtension: "otf")`
    static func pantonAMRegularOtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.pantonAMRegularOtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "PantonMtav3-Bold", withExtension: "otf")`
    static func pantonMtav3BoldOtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.pantonMtav3BoldOtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "PantonMtav3-ExtraBold", withExtension: "otf")`
    static func pantonMtav3ExtraBoldOtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.pantonMtav3ExtraBoldOtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "PantonMtav3-Regular", withExtension: "otf")`
    static func pantonMtav3RegularOtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.pantonMtav3RegularOtf
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.font` struct is generated, and contains static references to 21 fonts.
  struct font: Rswift.Validatable {
    /// Font `FiraGO-Bold`.
    static let firaGOBold = Rswift.FontResource(fontName: "FiraGO-Bold")
    /// Font `FiraGO-Book`.
    static let firaGOBook = Rswift.FontResource(fontName: "FiraGO-Book")
    /// Font `FiraGO-Eight`.
    static let firaGOEight = Rswift.FontResource(fontName: "FiraGO-Eight")
    /// Font `FiraGO-ExtraBold`.
    static let firaGOExtraBold = Rswift.FontResource(fontName: "FiraGO-ExtraBold")
    /// Font `FiraGO-ExtraLight`.
    static let firaGOExtraLight = Rswift.FontResource(fontName: "FiraGO-ExtraLight")
    /// Font `FiraGO-Four`.
    static let firaGOFour = Rswift.FontResource(fontName: "FiraGO-Four")
    /// Font `FiraGO-Hair`.
    static let firaGOHair = Rswift.FontResource(fontName: "FiraGO-Hair")
    /// Font `FiraGO-Heavy`.
    static let firaGOHeavy = Rswift.FontResource(fontName: "FiraGO-Heavy")
    /// Font `FiraGO-Light`.
    static let firaGOLight = Rswift.FontResource(fontName: "FiraGO-Light")
    /// Font `FiraGO-Medium`.
    static let firaGOMedium = Rswift.FontResource(fontName: "FiraGO-Medium")
    /// Font `FiraGO-Regular`.
    static let firaGORegular = Rswift.FontResource(fontName: "FiraGO-Regular")
    /// Font `FiraGO-SemiBold`.
    static let firaGOSemiBold = Rswift.FontResource(fontName: "FiraGO-SemiBold")
    /// Font `FiraGO-Thin`.
    static let firaGOThin = Rswift.FontResource(fontName: "FiraGO-Thin")
    /// Font `FiraGO-Two`.
    static let firaGOTwo = Rswift.FontResource(fontName: "FiraGO-Two")
    /// Font `FiraGO-UltraLight`.
    static let firaGOUltraLight = Rswift.FontResource(fontName: "FiraGO-UltraLight")
    /// Font `PantonAM-Bold`.
    static let pantonAMBold = Rswift.FontResource(fontName: "PantonAM-Bold")
    /// Font `PantonAM-ExtraBold`.
    static let pantonAMExtraBold = Rswift.FontResource(fontName: "PantonAM-ExtraBold")
    /// Font `PantonAM-Regular`.
    static let pantonAMRegular = Rswift.FontResource(fontName: "PantonAM-Regular")
    /// Font `PantonMtav3-Bold`.
    static let pantonMtav3Bold = Rswift.FontResource(fontName: "PantonMtav3-Bold")
    /// Font `PantonMtav3-ExtraBold`.
    static let pantonMtav3ExtraBold = Rswift.FontResource(fontName: "PantonMtav3-ExtraBold")
    /// Font `PantonMtav3-Regular`.
    static let pantonMtav3Regular = Rswift.FontResource(fontName: "PantonMtav3-Regular")

    /// `UIFont(name: "FiraGO-Bold", size: ...)`
    static func firaGOBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGOBold, size: size)
    }

    /// `UIFont(name: "FiraGO-Book", size: ...)`
    static func firaGOBook(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGOBook, size: size)
    }

    /// `UIFont(name: "FiraGO-Eight", size: ...)`
    static func firaGOEight(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGOEight, size: size)
    }

    /// `UIFont(name: "FiraGO-ExtraBold", size: ...)`
    static func firaGOExtraBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGOExtraBold, size: size)
    }

    /// `UIFont(name: "FiraGO-ExtraLight", size: ...)`
    static func firaGOExtraLight(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGOExtraLight, size: size)
    }

    /// `UIFont(name: "FiraGO-Four", size: ...)`
    static func firaGOFour(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGOFour, size: size)
    }

    /// `UIFont(name: "FiraGO-Hair", size: ...)`
    static func firaGOHair(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGOHair, size: size)
    }

    /// `UIFont(name: "FiraGO-Heavy", size: ...)`
    static func firaGOHeavy(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGOHeavy, size: size)
    }

    /// `UIFont(name: "FiraGO-Light", size: ...)`
    static func firaGOLight(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGOLight, size: size)
    }

    /// `UIFont(name: "FiraGO-Medium", size: ...)`
    static func firaGOMedium(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGOMedium, size: size)
    }

    /// `UIFont(name: "FiraGO-Regular", size: ...)`
    static func firaGORegular(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGORegular, size: size)
    }

    /// `UIFont(name: "FiraGO-SemiBold", size: ...)`
    static func firaGOSemiBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGOSemiBold, size: size)
    }

    /// `UIFont(name: "FiraGO-Thin", size: ...)`
    static func firaGOThin(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGOThin, size: size)
    }

    /// `UIFont(name: "FiraGO-Two", size: ...)`
    static func firaGOTwo(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGOTwo, size: size)
    }

    /// `UIFont(name: "FiraGO-UltraLight", size: ...)`
    static func firaGOUltraLight(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: firaGOUltraLight, size: size)
    }

    /// `UIFont(name: "PantonAM-Bold", size: ...)`
    static func pantonAMBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: pantonAMBold, size: size)
    }

    /// `UIFont(name: "PantonAM-ExtraBold", size: ...)`
    static func pantonAMExtraBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: pantonAMExtraBold, size: size)
    }

    /// `UIFont(name: "PantonAM-Regular", size: ...)`
    static func pantonAMRegular(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: pantonAMRegular, size: size)
    }

    /// `UIFont(name: "PantonMtav3-Bold", size: ...)`
    static func pantonMtav3Bold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: pantonMtav3Bold, size: size)
    }

    /// `UIFont(name: "PantonMtav3-ExtraBold", size: ...)`
    static func pantonMtav3ExtraBold(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: pantonMtav3ExtraBold, size: size)
    }

    /// `UIFont(name: "PantonMtav3-Regular", size: ...)`
    static func pantonMtav3Regular(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: pantonMtav3Regular, size: size)
    }

    static func validate() throws {
      if R.font.firaGOBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-Bold' could not be loaded, is 'FiraGO-Bold.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.firaGOBook(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-Book' could not be loaded, is 'FiraGO-Book.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.firaGOEight(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-Eight' could not be loaded, is 'FiraGO-Eight.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.firaGOExtraBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-ExtraBold' could not be loaded, is 'FiraGO-ExtraBold.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.firaGOExtraLight(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-ExtraLight' could not be loaded, is 'FiraGO-ExtraLight.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.firaGOFour(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-Four' could not be loaded, is 'FiraGO-Four.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.firaGOHair(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-Hair' could not be loaded, is 'FiraGO-Hair.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.firaGOHeavy(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-Heavy' could not be loaded, is 'FiraGO-Heavy.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.firaGOLight(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-Light' could not be loaded, is 'FiraGO-Light.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.firaGOMedium(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-Medium' could not be loaded, is 'FiraGO-Medium.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.firaGORegular(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-Regular' could not be loaded, is 'FiraGO-Regular.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.firaGOSemiBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-SemiBold' could not be loaded, is 'FiraGO-SemiBold.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.firaGOThin(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-Thin' could not be loaded, is 'FiraGO-Thin.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.firaGOTwo(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-Two' could not be loaded, is 'FiraGO-Two.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.firaGOUltraLight(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'FiraGO-UltraLight' could not be loaded, is 'FiraGO-UltraLight.ttf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.pantonAMBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'PantonAM-Bold' could not be loaded, is 'PantonAM-Bold.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.pantonAMExtraBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'PantonAM-ExtraBold' could not be loaded, is 'PantonAM-ExtraBold.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.pantonAMRegular(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'PantonAM-Regular' could not be loaded, is 'PantonAM-Regular.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.pantonMtav3Bold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'PantonMtav3-Bold' could not be loaded, is 'PantonMtav3-Bold.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.pantonMtav3ExtraBold(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'PantonMtav3-ExtraBold' could not be loaded, is 'PantonMtav3-ExtraBold.otf' added to the UIAppFonts array in this targets Info.plist?") }
      if R.font.pantonMtav3Regular(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'PantonMtav3-Regular' could not be loaded, is 'PantonMtav3-Regular.otf' added to the UIAppFonts array in this targets Info.plist?") }
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 3 images.
  struct image {
    /// Image `close`.
    static let close = Rswift.ImageResource(bundle: R.hostingBundle, name: "close")
    /// Image `face`.
    static let face = Rswift.ImageResource(bundle: R.hostingBundle, name: "face")
    /// Image `touch`.
    static let touch = Rswift.ImageResource(bundle: R.hostingBundle, name: "touch")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "close", bundle: ..., traitCollection: ...)`
    static func close(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.close, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "face", bundle: ..., traitCollection: ...)`
    static func face(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.face, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "touch", bundle: ..., traitCollection: ...)`
    static func touch(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.touch, compatibleWith: traitCollection)
    }
    #endif

    /// This `R.image.components` struct is generated, and contains static references to 0 images.
    struct components {
      /// This `R.image.components.gameLauncher` struct is generated, and contains static references to 1 images.
      struct gameLauncher {
        /// Image `in`.
        static let `in` = Rswift.ImageResource(bundle: R.hostingBundle, name: "Components/GameLauncher/in")

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "in", bundle: ..., traitCollection: ...)`
        static func `in`(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.components.gameLauncher.`in`, compatibleWith: traitCollection)
        }
        #endif

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    /// This `R.image.shared` struct is generated, and contains static references to 1 images.
    struct shared {
      /// Image `search`.
      static let search = Rswift.ImageResource(bundle: R.hostingBundle, name: "Shared/search")

      #if os(iOS) || os(tvOS)
      /// `UIImage(named: "search", bundle: ..., traitCollection: ...)`
      static func search(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
        return UIKit.UIImage(resource: R.image.shared.search, compatibleWith: traitCollection)
      }
      #endif

      /// This `R.image.shared.navBar` struct is generated, and contains static references to 1 images.
      struct navBar {
        /// Image `profile`.
        static let profile = Rswift.ImageResource(bundle: R.hostingBundle, name: "Shared/NavBar/profile")

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "profile", bundle: ..., traitCollection: ...)`
        static func profile(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.shared.navBar.profile, compatibleWith: traitCollection)
        }
        #endif

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    /// This `R.image.tabBar` struct is generated, and contains static references to 4 images.
    struct tabBar {
      /// Image `home`.
      static let home = Rswift.ImageResource(bundle: R.hostingBundle, name: "TabBar/home")
      /// Image `notification`.
      static let notification = Rswift.ImageResource(bundle: R.hostingBundle, name: "TabBar/notification")
      /// Image `promotions`.
      static let promotions = Rswift.ImageResource(bundle: R.hostingBundle, name: "TabBar/promotions")
      /// Image `sports`.
      static let sports = Rswift.ImageResource(bundle: R.hostingBundle, name: "TabBar/sports")

      #if os(iOS) || os(tvOS)
      /// `UIImage(named: "home", bundle: ..., traitCollection: ...)`
      static func home(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
        return UIKit.UIImage(resource: R.image.tabBar.home, compatibleWith: traitCollection)
      }
      #endif

      #if os(iOS) || os(tvOS)
      /// `UIImage(named: "notification", bundle: ..., traitCollection: ...)`
      static func notification(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
        return UIKit.UIImage(resource: R.image.tabBar.notification, compatibleWith: traitCollection)
      }
      #endif

      #if os(iOS) || os(tvOS)
      /// `UIImage(named: "promotions", bundle: ..., traitCollection: ...)`
      static func promotions(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
        return UIKit.UIImage(resource: R.image.tabBar.promotions, compatibleWith: traitCollection)
      }
      #endif

      #if os(iOS) || os(tvOS)
      /// `UIImage(named: "sports", bundle: ..., traitCollection: ...)`
      static func sports(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
        return UIKit.UIImage(resource: R.image.tabBar.sports, compatibleWith: traitCollection)
      }
      #endif

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.nib` struct is generated, and contains static references to 6 nibs.
  struct nib {
    /// Nib `GameLauncherCollectionViewCell`.
    static let gameLauncherCollectionViewCell = _R.nib._GameLauncherCollectionViewCell()
    /// Nib `GameLauncherComponentView`.
    static let gameLauncherComponentView = _R.nib._GameLauncherComponentView()
    /// Nib `PlayedGameLauncherCollectionViewCell`.
    static let playedGameLauncherCollectionViewCell = _R.nib._PlayedGameLauncherCollectionViewCell()
    /// Nib `PlayedGameLauncherComponentView`.
    static let playedGameLauncherComponentView = _R.nib._PlayedGameLauncherComponentView()
    /// Nib `RecentlyPlayedCollectionViewCell`.
    static let recentlyPlayedCollectionViewCell = _R.nib._RecentlyPlayedCollectionViewCell()
    /// Nib `RecentlyPlayedComponentView`.
    static let recentlyPlayedComponentView = _R.nib._RecentlyPlayedComponentView()

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "GameLauncherCollectionViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.gameLauncherCollectionViewCell) instead")
    static func gameLauncherCollectionViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.gameLauncherCollectionViewCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "GameLauncherComponentView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.gameLauncherComponentView) instead")
    static func gameLauncherComponentView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.gameLauncherComponentView)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "PlayedGameLauncherCollectionViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.playedGameLauncherCollectionViewCell) instead")
    static func playedGameLauncherCollectionViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.playedGameLauncherCollectionViewCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "PlayedGameLauncherComponentView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.playedGameLauncherComponentView) instead")
    static func playedGameLauncherComponentView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.playedGameLauncherComponentView)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "RecentlyPlayedCollectionViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.recentlyPlayedCollectionViewCell) instead")
    static func recentlyPlayedCollectionViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.recentlyPlayedCollectionViewCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "RecentlyPlayedComponentView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.recentlyPlayedComponentView) instead")
    static func recentlyPlayedComponentView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.recentlyPlayedComponentView)
    }
    #endif

    static func gameLauncherCollectionViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> GameLauncherCollectionViewCell? {
      return R.nib.gameLauncherCollectionViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? GameLauncherCollectionViewCell
    }

    static func gameLauncherComponentView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.gameLauncherComponentView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    static func playedGameLauncherCollectionViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> PlayedGameLauncherCollectionViewCell? {
      return R.nib.playedGameLauncherCollectionViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? PlayedGameLauncherCollectionViewCell
    }

    static func playedGameLauncherComponentView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.playedGameLauncherComponentView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    static func recentlyPlayedCollectionViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> RecentlyPlayedCollectionViewCell? {
      return R.nib.recentlyPlayedCollectionViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? RecentlyPlayedCollectionViewCell
    }

    static func recentlyPlayedComponentView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.recentlyPlayedComponentView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localization` struct is generated, and contains static references to 9 localization keys.
    struct localization {
      /// en translation: Games
      ///
      /// Locales: en, ka, hy
      static let home_page_title = Rswift.StringResource(key: "home_page_title", tableName: "Localization", bundle: R.hostingBundle, locales: ["en", "ka", "hy"], comment: nil)
      /// en translation: Join Now
      ///
      /// Locales: en, ka, hy
      static let join_now = Rswift.StringResource(key: "join_now", tableName: "Localization", bundle: R.hostingBundle, locales: ["en", "ka", "hy"], comment: nil)
      /// en translation: Login
      ///
      /// Locales: en, ka, hy
      static let login = Rswift.StringResource(key: "login", tableName: "Localization", bundle: R.hostingBundle, locales: ["en", "ka", "hy"], comment: nil)
      /// en translation: Notifications
      ///
      /// Locales: en, ka, hy
      static let notifications_page_title = Rswift.StringResource(key: "notifications_page_title", tableName: "Localization", bundle: R.hostingBundle, locales: ["en", "ka", "hy"], comment: nil)
      /// en translation: Promotions
      ///
      /// Locales: en, ka, hy
      static let promotions_page_title = Rswift.StringResource(key: "promotions_page_title", tableName: "Localization", bundle: R.hostingBundle, locales: ["en", "ka", "hy"], comment: nil)
      /// en translation: Recently Played
      ///
      /// Locales: en, ka, hy
      static let recently_played = Rswift.StringResource(key: "recently_played", tableName: "Localization", bundle: R.hostingBundle, locales: ["en", "ka", "hy"], comment: nil)
      /// en translation: Search for games
      ///
      /// Locales: en, ka, hy
      static let home_search_placeholder = Rswift.StringResource(key: "home_search_placeholder", tableName: "Localization", bundle: R.hostingBundle, locales: ["en", "ka", "hy"], comment: nil)
      /// en translation: Sports
      ///
      /// Locales: en, ka, hy
      static let sports_page_title = Rswift.StringResource(key: "sports_page_title", tableName: "Localization", bundle: R.hostingBundle, locales: ["en", "ka", "hy"], comment: nil)
      /// en translation: View All
      ///
      /// Locales: en, ka, hy
      static let view_all = Rswift.StringResource(key: "view_all", tableName: "Localization", bundle: R.hostingBundle, locales: ["en", "ka", "hy"], comment: nil)

      /// en translation: Games
      ///
      /// Locales: en, ka, hy
      static func home_page_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("home_page_title", tableName: "Localization", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localization", preferredLanguages: preferredLanguages) else {
          return "home_page_title"
        }

        return NSLocalizedString("home_page_title", tableName: "Localization", bundle: bundle, comment: "")
      }

      /// en translation: Join Now
      ///
      /// Locales: en, ka, hy
      static func join_now(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("join_now", tableName: "Localization", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localization", preferredLanguages: preferredLanguages) else {
          return "join_now"
        }

        return NSLocalizedString("join_now", tableName: "Localization", bundle: bundle, comment: "")
      }

      /// en translation: Login
      ///
      /// Locales: en, ka, hy
      static func login(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("login", tableName: "Localization", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localization", preferredLanguages: preferredLanguages) else {
          return "login"
        }

        return NSLocalizedString("login", tableName: "Localization", bundle: bundle, comment: "")
      }

      /// en translation: Notifications
      ///
      /// Locales: en, ka, hy
      static func notifications_page_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("notifications_page_title", tableName: "Localization", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localization", preferredLanguages: preferredLanguages) else {
          return "notifications_page_title"
        }

        return NSLocalizedString("notifications_page_title", tableName: "Localization", bundle: bundle, comment: "")
      }

      /// en translation: Promotions
      ///
      /// Locales: en, ka, hy
      static func promotions_page_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("promotions_page_title", tableName: "Localization", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localization", preferredLanguages: preferredLanguages) else {
          return "promotions_page_title"
        }

        return NSLocalizedString("promotions_page_title", tableName: "Localization", bundle: bundle, comment: "")
      }

      /// en translation: Recently Played
      ///
      /// Locales: en, ka, hy
      static func recently_played(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("recently_played", tableName: "Localization", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localization", preferredLanguages: preferredLanguages) else {
          return "recently_played"
        }

        return NSLocalizedString("recently_played", tableName: "Localization", bundle: bundle, comment: "")
      }

      /// en translation: Search for games
      ///
      /// Locales: en, ka, hy
      static func home_search_placeholder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("home_search_placeholder", tableName: "Localization", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localization", preferredLanguages: preferredLanguages) else {
          return "home_search_placeholder"
        }

        return NSLocalizedString("home_search_placeholder", tableName: "Localization", bundle: bundle, comment: "")
      }

      /// en translation: Sports
      ///
      /// Locales: en, ka, hy
      static func sports_page_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("sports_page_title", tableName: "Localization", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localization", preferredLanguages: preferredLanguages) else {
          return "sports_page_title"
        }

        return NSLocalizedString("sports_page_title", tableName: "Localization", bundle: bundle, comment: "")
      }

      /// en translation: View All
      ///
      /// Locales: en, ka, hy
      static func view_all(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("view_all", tableName: "Localization", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localization", preferredLanguages: preferredLanguages) else {
          return "view_all"
        }

        return NSLocalizedString("view_all", tableName: "Localization", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try nib.validate()
    #endif
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _GameLauncherComponentView.validate()
    }

    struct _GameLauncherCollectionViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "GameLauncherCollectionViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> GameLauncherCollectionViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? GameLauncherCollectionViewCell
      }

      fileprivate init() {}
    }

    struct _GameLauncherComponentView: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "GameLauncherComponentView"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      static func validate() throws {
        if UIKit.UIImage(named: "Components/GameLauncher/in", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Components/GameLauncher/in' is used in nib 'GameLauncherComponentView', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }

    struct _PlayedGameLauncherCollectionViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "PlayedGameLauncherCollectionViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> PlayedGameLauncherCollectionViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? PlayedGameLauncherCollectionViewCell
      }

      fileprivate init() {}
    }

    struct _PlayedGameLauncherComponentView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "PlayedGameLauncherComponentView"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      fileprivate init() {}
    }

    struct _RecentlyPlayedCollectionViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "RecentlyPlayedCollectionViewCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> RecentlyPlayedCollectionViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? RecentlyPlayedCollectionViewCell
      }

      fileprivate init() {}
    }

    struct _RecentlyPlayedComponentView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "RecentlyPlayedComponentView"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }
  #endif

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try home.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try login.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try mainTabBar.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try notifications.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try promotions.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try sports.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct home: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = HomeViewController

      let bundle = R.hostingBundle
      let homeViewController = StoryboardViewControllerResource<HomeViewController>(identifier: "HomeViewController")
      let name = "Home"

      func homeViewController(_: Void = ()) -> HomeViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: homeViewController)
      }

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.home().homeViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'homeViewController' could not be loaded from storyboard 'Home' as 'HomeViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct login: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController

      let appNavigationController = StoryboardViewControllerResource<AppNavigationController>(identifier: "AppNavigationController")
      let bundle = R.hostingBundle
      let loginViewController = StoryboardViewControllerResource<LoginViewController>(identifier: "LoginViewController")
      let name = "Login"
      let welcomeViewController = StoryboardViewControllerResource<WelcomeViewController>(identifier: "WelcomeViewController")

      func appNavigationController(_: Void = ()) -> AppNavigationController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: appNavigationController)
      }

      func loginViewController(_: Void = ()) -> LoginViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: loginViewController)
      }

      func welcomeViewController(_: Void = ()) -> WelcomeViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: welcomeViewController)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "face", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'face' is used in storyboard 'Login', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.login().appNavigationController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'appNavigationController' could not be loaded from storyboard 'Login' as 'AppNavigationController'.") }
        if _R.storyboard.login().loginViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'loginViewController' could not be loaded from storyboard 'Login' as 'LoginViewController'.") }
        if _R.storyboard.login().welcomeViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'welcomeViewController' could not be loaded from storyboard 'Login' as 'WelcomeViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct mainTabBar: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController

      let bundle = R.hostingBundle
      let mainTabBarViewController = StoryboardViewControllerResource<MainTabBarViewController>(identifier: "MainTabBarViewController")
      let name = "MainTabBar"

      func mainTabBarViewController(_: Void = ()) -> MainTabBarViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: mainTabBarViewController)
      }

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.mainTabBar().mainTabBarViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'mainTabBarViewController' could not be loaded from storyboard 'MainTabBar' as 'MainTabBarViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct notifications: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = NotificationsViewController

      let bundle = R.hostingBundle
      let name = "Notifications"
      let notificationsViewController = StoryboardViewControllerResource<NotificationsViewController>(identifier: "NotificationsViewController")

      func notificationsViewController(_: Void = ()) -> NotificationsViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: notificationsViewController)
      }

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.notifications().notificationsViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'notificationsViewController' could not be loaded from storyboard 'Notifications' as 'NotificationsViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct promotions: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "Promotions"
      let promotionsViewController = StoryboardViewControllerResource<PromotionsViewController>(identifier: "PromotionsViewController")

      func promotionsViewController(_: Void = ()) -> PromotionsViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: promotionsViewController)
      }

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.promotions().promotionsViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'promotionsViewController' could not be loaded from storyboard 'Promotions' as 'PromotionsViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct sports: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = SportsViewController

      let bundle = R.hostingBundle
      let name = "Sports"
      let sportsViewController = StoryboardViewControllerResource<SportsViewController>(identifier: "SportsViewController")

      func sportsViewController(_: Void = ()) -> SportsViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: sportsViewController)
      }

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.sports().sportsViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'sportsViewController' could not be loaded from storyboard 'Sports' as 'SportsViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
